### PR TITLE
Fix CMake error.

### PR DESCRIPTION
**Pull request by bchretien**
CMake Error at CMakeLists.txt:26 (message):
  message called with incorrect number of arguments

### CODE REVIEW

**Comment by mikeferguson** [comment]
Thanks!

**Comment by cottsay** [comment]
Any chance we can get a version bump for this? Its preventing compiles on Fedora...

Thanks!

**Comment by bchretien** [comment]
Same here for Arch Linux (my patch is currently applied when building the package).

**Comment by mikeferguson** [comment]
0.1.2 released.

**Comment by cottsay** [comment]
Thanks

**Pull request merged**
