### PR TITLE
Use serialnumber in camera names

### LINKED ISSUE #100: StringID instead of serialnumber?
Is there any reason why the StringID of the device is used as serialnumber in the color/ir name instead of serialnumber? This breaks compared to `openni`, which does use the real serialnumber.

`openn`i: https://github.com/ros-drivers/openni_camera/blob/indigo-devel/openni_camera/src/nodelets/driver.cpp#L142
`openni2`: https://github.com/ros-drivers/openni2_camera/blob/noetic-devel/openni2_camera/src/openni2_driver.cpp#L145

Because of this difference the `camera_info_manager` throws a warning: https://github.com/ros-perception/image_common/blob/noetic-devel/camera_info_manager/src/camera_info_manager.cpp#L288

Update: The implementation in `openni2` produces names which are not unique. Multiple cameras of the same type get the same StringID, while the serial number is different of course.
As these names are also used in calibration files, an unique name is needed. Therefore the solution of `openni` is the only correct one IMO.

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
Fixes #100

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
@reinzor @awesomebytes who is the best person to review this?

**Comment by MatthijsBurgh** [comment]
@mikeferguson @130s could you maybe take a look at this?

**Review by 130s — CHANGES_REQUESTED** [review]
- With a brief look, this looks good (i.e. esp. backward compatible). Can you confirm?
- Would you mind adding operational change if any in https://github.com/ros-drivers/openni2_camera/blob/noetic-devel/openni2_launch/doc/index.rst?

**Review by mikeferguson — APPROVED** [review]
Backwards compatibility looks correct to me - only suggestion is perhaps the ros parameter name should be more descriptive/clear - something like "use_serialnumber_as_name" (but maybe others thing name_serialnumber is descriptive enough - I don't feel strongly on this)

**Comment by MatthijsBurgh** [comment]
@130s @mikeferguson
- Backwards compatibility is 100%. By using the default (false), the behaviour doesn't change at all.
- I have renamed the parameter to `serialnumber_as_name`. I think this is much clearer.
- I don't think there are any changes that should be documented in file you suggested. I do have added it to the launch files (Which I cleaned a bit).

**Review by mikeferguson — APPROVED** [review]
Continues to look good to me - I'll give @130s a few days to review.

**Review by 130s — APPROVED** [review]
> - I don't think there are any changes that should be documented in file you suggested. I do have added it to the launch files (Which I cleaned a bit).

Well technically for those users who want to utilize the new options via launch file, there's an operational change (i.e. how to enable those options). However I _guess_ a convention might be that those who are familiar enough with ROS to execute camera driver they can easily figure out the usage by looking at the out-most launch (openni2.launch). So I'm +1.

(I've increasingly dealt with experienced engineers who don't have prior knowledge about ROS. I fee like for some of those people these undocumented convention is still difficult)

**Comment by 130s** [comment]
And I think this is valuable to backport to prior releases (ROS Melodic, Kinetic). I'm on it now. After that I can release and trigger binary pkg generation.

**Comment by MatthijsBurgh** [comment]
I think the noetic-devel branch can be used for the Melodic release. I don't know about Kinetic.

**Comment by 130s** [comment]
- For Melodic the [one registered](https://github.com/ros/rosdistro/blob/364bebb6f4c1ce0557fb0ac84dea747d4a30ec01/melodic/distribution.yaml#L7644) as of today is `indigo-devel`. Looking at https://github.com/ros-drivers/openni2_camera/pull/98 the only diff needed b/w ROS M and N is manifest change, which is trivial. But honestly I don't forsee many changes to come in for this pkg so I'm fine to keep separate branches for now (don't touch what's been working principle) unless people think differently.
- Technically this PR is a new feature, let alone bugfix. ROS community is a bit more proactive in adding new features into already-released distro (compared to e.g. `apt`/Ubuntu). I suggest a "happy-medium": Release this into Noetic and Melodic, but not to Kinetic (which is about to EoL in a few months). If there's convincing voices to support Kinetic release we can as well.

**Comment by 130s** [comment]
Let's move the release conversation to https://github.com/ros-drivers/openni2_camera/issues/103

**Pull request merged**
