### PR TITLE
fix compile on kinetic

### PR DESCRIPTION
**Pull request by jackieokay**
Following Tully's suggestion from #43 to fix the Kinetic binary job.

### CODE REVIEW

**Comment by tfoote** [comment]
+1 that looks right to me

**Comment by jack-oquin** [comment]
Any idea why this problem suddenly started manifesting itself?

**Comment by jackieokay** [comment]
@tfoote thinks that it succeeded previously due to a race condition. I suppose you could check this theory by using `-j1`.

I'm not so sure myself. I was able to reproduce the failure reliably on Xenial using catkin_tools. (I believe the Kinetic buildfarm uses catkin_make.) It may be related to stricter behavior in the new version of CMake on Xenial.

**Comment by tfoote** [comment]
@jack-oquin I suspect that the newer versions of make have a slightly different default execution order for targets that are not specified as a dependency. If there are targets A and B and they don't have a dependency between them A or B might go first. 

@jacquelinekay it's can be minimized with `-j1` but that won't necessarily fix it it defaults to building B then A. With parallel jobs A and B can get built simultaneously so B will never have A's output.

**Comment by jack-oquin** [comment]
Thanks for the info, that makes sense. 

It always bugs me when things start failing (or working) for unknown reasons. 

Thanks for the patch!

**Comment by 130s** [comment]
+1

**Comment by jackieokay** [comment]
It seems like this has multiple approvals but I don't have write permissions here, waiting on someone else to merge it.

**Comment by mikeferguson** [comment]
as soon as the devel job makes it through the farm, I'll do a new release

**Pull request merged**
