### PR TITLE
Add exposure time control

### PR DESCRIPTION
**Pull request by taketwo**
This pull request adds getter/setter methods for exposure time and a dynamic reconfigure option to manipulate this setting.

### CODE REVIEW

**Comment by taketwo** [comment]
Are there any issues with this patch?

**Comment by taketwo** [comment]
Hey, this is a very trivial patch. Is there any chance of merging it soon?

**Comment by 130s** [comment]
Do you think of any tests to be added to your PR?

**Comment by taketwo** [comment]
I do not think so. This PR adds a trivial wrapper around a driver API function, nothing to test.

**Comment by mikeferguson** [comment]
@taketwo -- not sure how, but I completely missed this PR. I'm not in the office right now to test on hardware, as soon as I get back I will test this. Just looking over it, looks good, but I have a complete set of prime sense devices I test against to make sure certain hardware doesn't cause particular regressions.

**Comment by taketwo** [comment]
No worries, thanks for taking care.
By the way, some Xtions seem to ignore this command. (From my experience, these are devices with serial numbers starting with 12.)

**Comment by taketwo** [comment]
@mikeferguson Any chance for a new release including this patch?

**Comment by 130s** [comment]
> Any chance for a new release including this patch?

Done https://github.com/ros-drivers/openni2_camera/issues/49#issuecomment-325248736
Binary should become available in the next public sync (watch https://discourse.ros.org/c/release if interested).

**Pull request merged**
