### PR TITLE
add usb_reset

### PR DESCRIPTION
**Pull request by k-okada**

### CODE REVIEW

**Comment by garaemon** [comment]
Could you release new version including this patch?

**Comment by mikeferguson** [comment]
I'll get a new release out tonight

**Comment by garaemon** [comment]
thanks!!

2014年12月9日火曜日、Michael Fergusonnotifications@github.comさんは書きました:

> I'll get a new release out tonight
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ros-drivers/openni2_camera/pull/22#issuecomment-66151251
> .

## 

from iPhone

**Comment by mikeferguson** [comment]
So, this should already be released in 0.1.4 in Hydro and 0.2.2 in Indigo -- are you having a specific problem?

**Comment by garaemon** [comment]
thanks again.
Our kinect mounted on PR2 sometimes gets blackout images... and I want to call usb_reset to restart kinect.

**Pull request merged**
