### PR TITLE
Release for Noetic

### PR DESCRIPTION
**Pull request by 130s**
# Changes made
- Release info.
- CI update to remove old stuff and add Noetic support.
- If needed, add Noetic support cont'd from https://github.com/ros-drivers/openni2_camera/pull/97

# Branch
- Based off of `indigo-devel` (which is used for up to [ROS Melodic release](https://github.com/ros/rosdistro/blob/8b9be633f139711620a4ba8e239874ac0ae063b9/melodic/distribution.yaml#L6674))
- Target: `noetic-devel` (which I just branched off of `indigo-devel`).

# CoS
- [ ] CI cnofig update. CI should pass.

### CODE REVIEW

**Comment by 130s** [comment]
Travis CI job for noetic fails https://travis-ci.org/github/ros-drivers/openni2_camera/jobs/694065338#L439 looking for a released .deb of rgbd_launch

**Comment by mikeferguson** [comment]
looks like you also merged my noetic fixes into indigo-devel, but not noetic-devel branch

**Comment by 130s** [comment]
With a recent issue with the released version of `catkin_tools` https://github.com/catkin/catkin_tools/issues/594#issuecomment-638449890, all CI jobs on travis failed.

I go ahead and make a release to rosdistro. Because there's already a hold [discourse.ros.org#14451](https://discourse.ros.org/t/preparing-for-noetic-sync-2020-06-05/14451), release may get stuck though.

**Comment by 130s** [comment]
> looks like you also merged my noetic fixes into indigo-devel, but not noetic-devel branch

Thanks for the headup. My understanding, can be wrong though, is that the changes added in https://github.com/ros-drivers/openni2_camera/pull/97, which is package format 3 change, work even on indigo as format 3 support is done in `catkin_pkg`, which is agnostic to distro of OS and ROS. 

I leave it as is on both indigo branch (used for indigo before noetic) and noetic branch for now unless there's an issue with this.

**Pull request merged**
