### PR TITLE
Added the ability to resolve device ids like "#1" to actual device URIs.

### PR DESCRIPTION
**Pull request by stwirth**
Resolves ros-drivers/openni2_camera#2

### CODE REVIEW

**Comment by jkammerl** [comment]
Thanks!

**Comment by jkammerl** [comment]
oh, I don't have permissions to accept this pull request. Your patch looks good to me!

**Comment by stwirth** [comment]
@jonbinney Can you give the author and maintainer access to his package (and accept this PR if you are already here)?

**Comment by jonbinney** [comment]
Merging. Also gave the ros-drivers/openni team commit rights to the repo

**Comment by stwirth** [comment]
Thanks!

**Pull request merged**
